# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "cn"

# About/contact
author:
  name:       zmj
  url:        https://zmjzmjzmj8.github.io/githubMj.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
